import { LandRecord } from '@/types';
import { createDefaultDocumentList } from './documentRequirements';

export const INITIAL_MOCK_RECORDS: LandRecord[] = [
  {
    id: 'HS-2026-001',
    createdAt: '2026-03-01T08:30:00Z',
    updatedAt: '2026-03-05T14:20:00Z',
    customerName: 'Nguyễn Văn Hùng',
    customerIdNumber: '001088012345',
    customerPhone: '0912345678',
    customerAddress: 'Số 15 Phố Duy Tân, Cầu Giấy, Hà Nội',
    coOwnerName: 'Trần Thị Thu (Vợ)',
    recordType: 'chuyen_nhuong',
    landAddress: 'Thửa 45, Tổ 3, Phường Mỹ Đình 2, Quận Nam Từ Liêm, Hà Nội',
    plotNumber: '45',
    mapSheetNumber: '12',
    area: 95.5,
    landType: 'ONT (Đất ở tại nông thôn)',
    certificateNumber: 'CS 982134',
    certificateBookNumber: 'CH-00129',
    landNotes: 'Đất quy hoạch khu dân cư hiện hữu, không vướng quy hoạch mở đường',
    documents: [
      {
        id: 'doc_gcn_goc',
        name: 'Giấy chứng nhận (Sổ đỏ / Sổ hồng) bản gốc',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Bản chính phôi sổ đỏ/sổ hồng để nộp đăng bộ sang tên',
        files: [
          {
            id: 'file_01',
            name: 'So_do_goc_CS982134.pdf',
            size: 2450000,
            type: 'application/pdf',
            uploadDate: '2026-03-01',
          },
        ],
      },
      {
        id: 'doc_cccd_2ben',
        name: 'CCCD của bên chuyển nhượng & bên nhận chuyển nhượng',
        required: true,
        submitted: true,
        originalType: 'certified_copy',
        description: 'Bản sao công chứng hoặc bản chụp CCCD gắn chip 2 mặt',
        files: [],
      },
      {
        id: 'doc_hon_nhan',
        name: 'Giấy đăng ký kết hôn / Giấy xác nhận độc thân',
        required: true,
        submitted: true,
        originalType: 'certified_copy',
        description: 'Chứng minh tài sản chung hay riêng của các bên',
        files: [],
      },
      {
        id: 'doc_hd_cong_chung',
        name: 'Hợp đồng chuyển nhượng quyền sử dụng đất có công chứng',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Tối thiểu 03 bản chính công chứng',
        files: [
          {
            id: 'file_02',
            name: 'Hop_dong_cong_chung_VPCC_ThangLong.pdf',
            size: 1820000,
            type: 'application/pdf',
            uploadDate: '2026-03-02',
          },
        ],
      },
      {
        id: 'doc_to_khai_thue',
        name: 'Tờ khai thuế TNCN và Tờ khai lệ phí trước bạ',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Kèm mã số thuế cá nhân của 2 bên',
        files: [],
      },
    ],
    receivedDate: '2026-03-01',
    assignedOfficer: 'Lê Văn Minh (Chuyên viên Pháp lý)',
    processingAgency: 'Chi nhánh Văn phòng Đăng ký đất đai Nam Từ Liêm',
    status: 'dang_xu_ly',
    submittedDate: '2026-03-02',
    expectedReturnDate: '2026-03-18',
    progressLogs: [
      {
        id: 'log_01',
        date: '2026-03-01',
        status: 'tiep_nhan',
        note: 'Tiếp nhận hồ sơ chuyển nhượng từ khách hàng Nguyễn Văn Hùng',
        officer: 'Lê Văn Minh',
      },
      {
        id: 'log_02',
        date: '2026-03-02',
        status: 'dang_xu_ly',
        note: 'Đã nộp hồ sơ vào Bộ phận Một cửa Nam Từ Liêm, nhận giấy hẹn ngày 18/03/2026',
        officer: 'Lê Văn Minh',
      },
    ],
    serviceFee: 15000000,
    depositAmount: 5000000,
    paidAmount: 5000000,
    remainingAmount: 10000000,
    paymentStatus: 'da_tam_ung',
    paymentNotes: 'Khách đã cọc 5.000.000đ khi ký hợp đồng dịch vụ',
  },

  {
    id: 'HS-2026-002',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-03-06T10:15:00Z',
    customerName: 'Trần Thị Mai',
    customerIdNumber: '079190009876',
    customerPhone: '0908765432',
    customerAddress: 'Ấp 2, Xã Tân An Hội, Huyện Củ Chi, TP. Hồ Chí Minh',
    recordType: 'thua_ke',
    landAddress: 'Thửa 112, Tờ 8, Xã Tân Thạnh Đông, Huyện Củ Chi, TP. Hồ Chí Minh',
    plotNumber: '112',
    mapSheetNumber: '8',
    area: 320.0,
    landType: 'ODT + CLN (Đất ở đô thị 150m² + Cây lâu năm 170m²)',
    certificateNumber: 'BK 654321',
    certificateBookNumber: 'CH-99881',
    documents: [
      {
        id: 'doc_gcn_goc',
        name: 'Giấy chứng nhận (Sổ đỏ / Sổ hồng) bản gốc',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Bản chính của người để lại di sản',
        files: [],
      },
      {
        id: 'doc_trich_luc_khai_tu',
        name: 'Trích lục khai tử của người để lại di sản',
        required: true,
        submitted: true,
        originalType: 'certified_copy',
        description: 'Bản sao trích lục khai tử do UBND cấp',
        files: [],
      },
      {
        id: 'doc_van_ban_thua_ke',
        name: 'Văn bản thỏa thuận phân chia di sản / Khai nhận di sản / Di chúc',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Đã lập tại Văn phòng công chứng và niêm yết đủ ngày',
        files: [],
      },
      {
        id: 'doc_cccd_thua_ke',
        name: 'CCCD của tất cả những người thuộc hàng thừa kế',
        required: true,
        submitted: true,
        originalType: 'certified_copy',
        description: 'Bản sao có công chứng',
        files: [],
      },
      {
        id: 'doc_chung_minh_quan_he',
        name: 'Giấy khai sinh / ĐKKH chứng minh quan hệ thuộc hàng thừa kế',
        required: true,
        submitted: true,
        originalType: 'certified_copy',
        description: 'Cơ sở để miễn thuế TNCN và lệ phí trước bạ',
        files: [],
      },
    ],
    receivedDate: '2026-02-15',
    assignedOfficer: 'Hoàng Quốc Việt (Trưởng nhóm)',
    processingAgency: 'Chi cục Thuế khu vực Củ Chi & VPĐKĐĐ',
    status: 'cho_thue',
    submittedDate: '2026-02-20',
    expectedReturnDate: '2026-03-12',
    progressLogs: [
      {
        id: 'log_01',
        date: '2026-02-15',
        status: 'tiep_nhan',
        note: 'Tiếp nhận hồ sơ khai nhận di sản thừa kế',
        officer: 'Hoàng Quốc Việt',
      },
      {
        id: 'log_02',
        date: '2026-02-20',
        status: 'dang_xu_ly',
        note: 'Đã hoàn tất niêm yết công chứng 15 ngày tại UBND xã, chuyển hồ sơ qua Thuế',
        officer: 'Hoàng Quốc Việt',
      },
      {
        id: 'log_03',
        date: '2026-03-01',
        status: 'cho_thue',
        note: 'Đang đợi Chi cục thuế ra thông báo miễn thuế do thừa kế mẹ để lại cho con',
        officer: 'Hoàng Quốc Việt',
      },
    ],
    serviceFee: 20000000,
    depositAmount: 10000000,
    paidAmount: 10000000,
    remainingAmount: 10000000,
    paymentStatus: 'da_tam_ung',
  },

  {
    id: 'HS-2026-003',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-03-04T16:00:00Z',
    customerName: 'Phạm Đức Toàn',
    customerIdNumber: '038085006789',
    customerPhone: '0978112233',
    customerAddress: 'Phường Tam Hiệp, TP. Biên Hòa, Đồng Nai',
    recordType: 'cap_lan_dau',
    landAddress: 'Khu phố 3, Phường Trảng Dài, TP. Biên Hòa, Đồng Nai',
    plotNumber: '215',
    mapSheetNumber: '34',
    area: 180.0,
    landType: 'ONT (Đất ở nông thôn)',
    certificateNumber: 'Chưa có (Đang cấp lần đầu)',
    landNotes: 'Có giấy tạm cấp đất năm 1991 và bản trích lục 299/TTg',
    documents: [
      {
        id: 'doc_don_04dk',
        name: 'Đơn đăng ký, cấp Giấy chứng nhận (Mẫu 04/ĐK)',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Theo quy định Luật Đất đai 2024',
        files: [],
      },
      {
        id: 'doc_giay_to_cu_137',
        name: 'Giấy tờ chứng minh quyền SDĐ theo Điều 137 Luật Đất đai 2024',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Giấy giao đất cơ quan trước năm 1993',
        files: [],
      },
      {
        id: 'doc_trich_do_dia_chinh',
        name: 'Bản trích đo địa chính thửa đất / Bản vẽ hiện trạng',
        required: true,
        submitted: false,
        originalType: 'original',
        description: 'Cần bổ sung bản trích đo có đóng dấu của đơn vị đo đạc',
        files: [],
      },
      {
        id: 'doc_xac_nhan_ubnd_xa',
        name: 'Văn bản xác nhận của UBND cấp xã (sử dụng ổn định, không tranh chấp)',
        required: true,
        submitted: true,
        originalType: 'original',
        description: 'Đã được UBND phường Trảng Dài xác nhận',
        files: [],
      },
      {
        id: 'doc_cccd_chu_dat',
        name: 'CCCD và xác nhận thông tin cư trú của chủ sử dụng đất',
        required: true,
        submitted: true,
        originalType: 'certified_copy',
        files: [],
      },
    ],
    receivedDate: '2026-02-10',
    assignedOfficer: 'Đặng Thanh Tâm',
    processingAgency: 'UBND TP. Biên Hòa & VP Đăng ký đất đai Đồng Nai',
    status: 'cho_bo_sung',
    expectedReturnDate: '2026-04-10',
    progressLogs: [
      {
        id: 'log_01',
        date: '2026-02-10',
        status: 'tiep_nhan',
        note: 'Tiếp nhận hồ sơ xin cấp GCN lần đầu',
        officer: 'Đặng Thanh Tâm',
      },
      {
        id: 'log_02',
        date: '2026-03-04',
        status: 'cho_bo_sung',
        note: 'Văn phòng ĐKĐĐ yêu cầu bổ sung bản trích đo tọa độ địa chính mới nhất',
        officer: 'Đặng Thanh Tâm',
      },
    ],
    serviceFee: 25000000,
    depositAmount: 10000000,
    paidAmount: 10000000,
    remainingAmount: 15000000,
    paymentStatus: 'da_tam_ung',
  },

  {
    id: 'HS-2026-004',
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-02-28T11:00:00Z',
    customerName: 'Vũ Hải Đăng',
    customerIdNumber: '048092004567',
    customerPhone: '0935567890',
    customerAddress: 'Phường An Hải Bắc, Quận Sơn Trà, TP. Đà Nẵng',
    recordType: 'cap_doi',
    landAddress: 'Số 88 Đường Võ Văn Kiệt, Phường An Hải Đông, Quận Sơn Trà, TP. Đà Nẵng',
    plotNumber: '58',
    mapSheetNumber: '29',
    area: 120.0,
    landType: 'ODT (Đất ở tại đô thị)',
    certificateNumber: 'ĐK 776543 (Đổi sang phôi 2025)',
    certificateBookNumber: 'GCN-1029',
    documents: createDefaultDocumentList('cap_doi').map((d) => ({
      ...d,
      submitted: true,
    })),
    receivedDate: '2026-01-20',
    assignedOfficer: 'Phan Thu Hà',
    processingAgency: 'Chi nhánh VP Đăng ký đất đai Quận Sơn Trà',
    status: 'hoan_thanh',
    submittedDate: '2026-01-22',
    expectedReturnDate: '2026-02-15',
    actualReturnDate: '2026-02-14',
    progressLogs: [
      {
        id: 'log_01',
        date: '2026-01-20',
        status: 'tiep_nhan',
        note: 'Tiếp nhận sổ đỏ cũ bị ố mờ, đề nghị cấp đổi phôi mới 2025 có mã QR',
        officer: 'Phan Thu Hà',
      },
      {
        id: 'log_02',
        date: '2026-02-14',
        status: 'hoan_thanh',
        note: 'Đã nhận phôi Giấy chứng nhận mới từ Văn phòng ĐKĐĐ, đã sẵn sàng trả khách',
        officer: 'Phan Thu Hà',
      },
    ],
    serviceFee: 8000000,
    depositAmount: 4000000,
    paidAmount: 8000000,
    remainingAmount: 0,
    paymentStatus: 'da_tat_toan',
    paymentNotes: 'Khách đã thanh toán đủ 100% khi nhận sổ mới',
  },
];
